'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SMSMasivosWS
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://servicio.smsmasivos.com.ar/ws/", ConfigurationName:="SMSMasivosWS.SMSMasivosAPISoap")>  _
    Public Interface SMSMasivosAPISoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://servicio.smsmasivos.com.ar/ws/EnviarSMS", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function EnviarSMS(ByVal usuario As String, ByVal clave As String, ByVal numero As Long, ByVal texto As String, ByVal test As Boolean) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://servicio.smsmasivos.com.ar/ws/RecibirSMS", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RecibirSMS(ByVal usuario As String, ByVal clave As String, ByVal origen As String, ByVal solonoleidos As Boolean, ByVal marcarcomoleidos As Boolean) As SMSMasivosWS.clsRespuesta()
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://servicio.smsmasivos.com.ar/ws/")>  _
    Partial Public Class clsRespuesta
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private numeroField As Long
        
        Private textoField As String
        
        Private fechaField As Date
        
        Private idsmsField As Long
        
        Private idinternoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property numero() As Long
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
                Me.RaisePropertyChanged("numero")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property texto() As String
            Get
                Return Me.textoField
            End Get
            Set
                Me.textoField = value
                Me.RaisePropertyChanged("texto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
                Me.RaisePropertyChanged("fecha")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property idsms() As Long
            Get
                Return Me.idsmsField
            End Get
            Set
                Me.idsmsField = value
                Me.RaisePropertyChanged("idsms")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property idinterno() As String
            Get
                Return Me.idinternoField
            End Get
            Set
                Me.idinternoField = value
                Me.RaisePropertyChanged("idinterno")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SMSMasivosAPISoapChannel
        Inherits SMSMasivosWS.SMSMasivosAPISoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SMSMasivosAPISoapClient
        Inherits System.ServiceModel.ClientBase(Of SMSMasivosWS.SMSMasivosAPISoap)
        Implements SMSMasivosWS.SMSMasivosAPISoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function EnviarSMS(ByVal usuario As String, ByVal clave As String, ByVal numero As Long, ByVal texto As String, ByVal test As Boolean) As String Implements SMSMasivosWS.SMSMasivosAPISoap.EnviarSMS
            Return MyBase.Channel.EnviarSMS(usuario, clave, numero, texto, test)
        End Function
        
        Public Function RecibirSMS(ByVal usuario As String, ByVal clave As String, ByVal origen As String, ByVal solonoleidos As Boolean, ByVal marcarcomoleidos As Boolean) As SMSMasivosWS.clsRespuesta() Implements SMSMasivosWS.SMSMasivosAPISoap.RecibirSMS
            Return MyBase.Channel.RecibirSMS(usuario, clave, origen, solonoleidos, marcarcomoleidos)
        End Function
    End Class
End Namespace
